name: victoria_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  android_intent_plus: ^3.1.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: 4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  intl: ^0.17.0
  package_info_plus: ^3.0.1

dev_dependencies:
  logger: ^1.1.0
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIconData
      fonts:
        - asset: assets/fonts/CustomIconData.ttf
  assets:
    - assets/images/
    - assets/images/illustrations/
    - assets/images/placeholder/
    - assets/images/drawable/
    - assets/images/drawable/profile/
    - assets/fonts/
