name: victoria_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  android_intent_plus: ^3.1.5
  connectivity_plus: ^3.0.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.0.8
  firebase_auth: ^4.1.1
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  flutter_phoenix: ^1.1.0
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: 4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  http: ^0.13.5
  http_parser: ^4.0.2
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  location: ^4.4.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  rive: ^0.9.1
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  logger: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIconData
      fonts:
        - asset: assets/fonts/CustomIconData.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
  assets:
    - assets/images/
    - assets/images/illustrations/
    - assets/images/placeholder/
    - assets/images/drawable/
    - assets/images/drawable/profile/
    - assets/images/logo/
    - assets/fonts/
    - assets/rive/
